# config/multi_dataset_config.yaml

# Multi-dataset specific configurations
datasets:
  FD001:
    name: "Single Fault, Single Condition"
    fault_modes: 1
    operating_conditions: 1
    failure_threshold: 30
    complexity_weight: 1.0
  
  FD002:
    name: "Single Fault, Multiple Conditions"
    fault_modes: 1
    operating_conditions: 6
    failure_threshold: 25
    complexity_weight: 2.0
    
  FD003:
    name: "Multiple Faults, Single Condition" 
    fault_modes: 2
    operating_conditions: 1
    failure_threshold: 30
    complexity_weight: 2.5
    
  FD004:
    name: "Multiple Faults, Multiple Conditions"
    fault_modes: 2
    operating_conditions: 6
    failure_threshold: 20
    complexity_weight: 4.0

# Sensor mappings for all datasets
sensors:
  - temperature
  - pressure
  - vibration
  - rpm
  - oil_level
  - fuel_flow
  - altitude
  - speed

# Data preprocessing
data:
  test_size: 0.2
  random_state: 42
  synthetic_samples: 10000

# Model configurations optimized for multi-dataset training
models:
  random_forest:
    n_estimators: 150
    max_depth: 12
    random_state: 42
    
  xgboost:
    n_estimators: 150
    max_depth: 8
    learning_rate: 0.1
    
  lstm:
    units: 64
    dropout: 0.3
    epochs: 50
    batch_size: 64
    sequence_length: 30

# Alert thresholds
alerts:
  failure_threshold: 0.7
  warning_threshold: 0.4
  
# Ensemble configurations
ensemble:
  cross_dataset_weight: 0.6
  individual_dataset_weight: 0.4
  voting_strategy: "soft"